name: TickIt
description: A simple todo app in flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+010003

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0-nullsafety.0
  shared_preferences: ^0.5.4
  sqflite: ^2.0.0+2
  path: ^1.8.0
  flutter_local_notifications: 5.0.0-nullsafety.1 
  animations: ^2.0.0
  requests: ^3.3.0
  device_info: ^2.0.0
  connectivity: ^3.0.2

  #for the appicon
  #flutter_launcher_icons: ^0.9.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: ./assets/fonts/ProductSans-Light.ttf
    - family: Truculenta
      fonts:
        - asset: ./assets/fonts/Truculenta.ttf
  assets:
    - assets/icons/
    - assets/imgs/